// Generated by gencpp from file lsbot_msgs/SetAngleRequest.msg
// DO NOT EDIT!


#ifndef LSBOT_MSGS_MESSAGE_SETANGLEREQUEST_H
#define LSBOT_MSGS_MESSAGE_SETANGLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lsbot_msgs
{
template <class ContainerAllocator>
struct SetAngleRequest_
{
  typedef SetAngleRequest_<ContainerAllocator> Type;

  SetAngleRequest_()
    : angle(0.0)  {
    }
  SetAngleRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetAngleRequest_

typedef ::lsbot_msgs::SetAngleRequest_<std::allocator<void> > SetAngleRequest;

typedef boost::shared_ptr< ::lsbot_msgs::SetAngleRequest > SetAngleRequestPtr;
typedef boost::shared_ptr< ::lsbot_msgs::SetAngleRequest const> SetAngleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lsbot_msgs::SetAngleRequest_<ContainerAllocator1> & lhs, const ::lsbot_msgs::SetAngleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lsbot_msgs::SetAngleRequest_<ContainerAllocator1> & lhs, const ::lsbot_msgs::SetAngleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lsbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::lsbot_msgs::SetAngleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4edb55038e2b8889ULL;
  static const uint64_t static_value2 = 0x76a0c0c56935341cULL;
};

template<class ContainerAllocator>
struct DataType< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lsbot_msgs/SetAngleRequest";
  }

  static const char* value(const ::lsbot_msgs::SetAngleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Service to set an Angle to the floorscan\n"
"\n"
"float64 angle    # Angle in radians\n"
;
  }

  static const char* value(const ::lsbot_msgs::SetAngleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAngleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lsbot_msgs::SetAngleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lsbot_msgs::SetAngleRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSBOT_MSGS_MESSAGE_SETANGLEREQUEST_H
