// Generated by gencpp from file lsbot_msgs/SetAngle.msg
// DO NOT EDIT!


#ifndef LSBOT_MSGS_MESSAGE_SETANGLE_H
#define LSBOT_MSGS_MESSAGE_SETANGLE_H

#include <ros/service_traits.h>


#include <lsbot_msgs/SetAngleRequest.h>
#include <lsbot_msgs/SetAngleResponse.h>


namespace lsbot_msgs
{

struct SetAngle
{

typedef SetAngleRequest Request;
typedef SetAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAngle
} // namespace lsbot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lsbot_msgs::SetAngle > {
  static const char* value()
  {
    return "1b7413e2dbca4e7137bc2a82ebcf4118";
  }

  static const char* value(const ::lsbot_msgs::SetAngle&) { return value(); }
};

template<>
struct DataType< ::lsbot_msgs::SetAngle > {
  static const char* value()
  {
    return "lsbot_msgs/SetAngle";
  }

  static const char* value(const ::lsbot_msgs::SetAngle&) { return value(); }
};


// service_traits::MD5Sum< ::lsbot_msgs::SetAngleRequest> should match
// service_traits::MD5Sum< ::lsbot_msgs::SetAngle >
template<>
struct MD5Sum< ::lsbot_msgs::SetAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lsbot_msgs::SetAngle >::value();
  }
  static const char* value(const ::lsbot_msgs::SetAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lsbot_msgs::SetAngleRequest> should match
// service_traits::DataType< ::lsbot_msgs::SetAngle >
template<>
struct DataType< ::lsbot_msgs::SetAngleRequest>
{
  static const char* value()
  {
    return DataType< ::lsbot_msgs::SetAngle >::value();
  }
  static const char* value(const ::lsbot_msgs::SetAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lsbot_msgs::SetAngleResponse> should match
// service_traits::MD5Sum< ::lsbot_msgs::SetAngle >
template<>
struct MD5Sum< ::lsbot_msgs::SetAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lsbot_msgs::SetAngle >::value();
  }
  static const char* value(const ::lsbot_msgs::SetAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lsbot_msgs::SetAngleResponse> should match
// service_traits::DataType< ::lsbot_msgs::SetAngle >
template<>
struct DataType< ::lsbot_msgs::SetAngleResponse>
{
  static const char* value()
  {
    return DataType< ::lsbot_msgs::SetAngle >::value();
  }
  static const char* value(const ::lsbot_msgs::SetAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LSBOT_MSGS_MESSAGE_SETANGLE_H
