// Generated by gencpp from file lsbot_msgs/SpecsRotaryServoRequest.msg
// DO NOT EDIT!


#ifndef LSBOT_MSGS_MESSAGE_SPECSROTARYSERVOREQUEST_H
#define LSBOT_MSGS_MESSAGE_SPECSROTARYSERVOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lsbot_msgs
{
template <class ContainerAllocator>
struct SpecsRotaryServoRequest_
{
  typedef SpecsRotaryServoRequest_<ContainerAllocator> Type;

  SpecsRotaryServoRequest_()
    {
    }
  SpecsRotaryServoRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpecsRotaryServoRequest_

typedef ::lsbot_msgs::SpecsRotaryServoRequest_<std::allocator<void> > SpecsRotaryServoRequest;

typedef boost::shared_ptr< ::lsbot_msgs::SpecsRotaryServoRequest > SpecsRotaryServoRequestPtr;
typedef boost::shared_ptr< ::lsbot_msgs::SpecsRotaryServoRequest const> SpecsRotaryServoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace lsbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lsbot_msgs/SpecsRotaryServoRequest";
  }

  static const char* value(const ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# device features\n"
"\n"
;
  }

  static const char* value(const ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpecsRotaryServoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lsbot_msgs::SpecsRotaryServoRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LSBOT_MSGS_MESSAGE_SPECSROTARYSERVOREQUEST_H
