(cl:defpackage lsbot_msgs-srv
  (:use )
  (:export
   "SETANGLE"
   "<SETANGLE-REQUEST>"
   "SETANGLE-REQUEST"
   "<SETANGLE-RESPONSE>"
   "SETANGLE-RESPONSE"
   "SPECSROTARYSERVO"
   "<SPECSROTARYSERVO-REQUEST>"
   "SPECSROTARYSERVO-REQUEST"
   "<SPECSROTARYSERVO-RESPONSE>"
   "SPECSROTARYSERVO-RESPONSE"
  ))

